de_confs = Generate_Pfaffian_Detuning_Configs(...
    -20:1:20,cellfun(@(ld)new_lattice_config(ld,4),...
    {[4,4],[4,5],[5,5],[5,6],[6,6]},'UniformOutput',0));
confs = Get_Config_Data(de_confs);
save('detuning_data','confs');